create extension if not exists pgcrypto;

create table if not exists public.hdg_groups (
  group_key text primary key,
  group_name text not null default 'Harbu Darbu Gang',
  created_at timestamptz not null default now()
);

create table if not exists public.hdg_live (
  group_key text not null references public.hdg_groups(group_key) on delete cascade,
  room_code text not null,
  state jsonb not null,
  updated_at timestamptz not null default now(),
  primary key (group_key, room_code)
);

create table if not exists public.hdg_nights (
  id bigint generated by default as identity primary key,
  group_key text not null references public.hdg_groups(group_key) on delete cascade,
  night_date text not null,
  players jsonb not null default '[]'::jsonb,
  games jsonb not null default '[]'::jsonb,
  rebuys jsonb not null default '{}'::jsonb,
  cashout jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.hdg_groups enable row level security;
alter table public.hdg_live enable row level security;
alter table public.hdg_nights enable row level security;

revoke all on public.hdg_groups from anon, authenticated;
revoke all on public.hdg_live from anon, authenticated;
revoke all on public.hdg_nights from anon, authenticated;

create or replace function public.hdg_check_group(p_group_key text)
returns boolean
language sql
security definer
set search_path=public
as $$
  select exists(select 1 from public.hdg_groups where group_key = p_group_key);
$$;

create or replace function public.hdg_save_live(p_group_key text, p_room_code text, p_state jsonb)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.hdg_groups where group_key=p_group_key) then
    raise exception 'Invalid group access';
  end if;
  insert into public.hdg_live(group_key,room_code,state,updated_at)
  values(p_group_key,upper(p_room_code),p_state,now())
  on conflict(group_key,room_code)
  do update set state=excluded.state,updated_at=now();
end;
$$;

create or replace function public.hdg_get_live(p_group_key text, p_room_code text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare result jsonb;
begin
  if not exists(select 1 from public.hdg_groups where group_key=p_group_key) then
    raise exception 'Invalid group access';
  end if;
  select state into result
  from public.hdg_live
  where group_key=p_group_key and room_code=upper(p_room_code)
  order by updated_at desc
  limit 1;
  return result;
end;
$$;

create or replace function public.hdg_get_open_night(p_group_key text)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare result jsonb;
begin
  if not exists(select 1 from public.hdg_groups where group_key=p_group_key) then
    raise exception 'Invalid group access';
  end if;
  select state into result
  from public.hdg_live
  where group_key=p_group_key
  order by updated_at desc
  limit 1;
  return result;
end;
$$;

create or replace function public.hdg_close_night(p_group_key text, p_state jsonb)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.hdg_groups where group_key=p_group_key) then
    raise exception 'Invalid group access';
  end if;
  insert into public.hdg_nights(group_key,night_date,players,games,rebuys,cashout)
  values(
    p_group_key,
    coalesce(p_state->>'date',''),
    coalesce(p_state->'players','[]'::jsonb),
    coalesce(p_state->'games','[]'::jsonb),
    coalesce(p_state->'rebuys','{}'::jsonb),
    coalesce(p_state->'cashout','{}'::jsonb)
  );
  delete from public.hdg_live
  where group_key=p_group_key and room_code=upper(coalesce(p_state->>'room',''));
end;
$$;

create or replace function public.hdg_get_old_nights(p_group_key text)
returns table(
  id bigint,
  night_date text,
  players jsonb,
  games jsonb,
  rebuys jsonb,
  cashout jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.hdg_groups where group_key=p_group_key) then
    raise exception 'Invalid group access';
  end if;
  return query
  select n.id,n.night_date,n.players,n.games,n.rebuys,n.cashout,n.created_at
  from public.hdg_nights n
  where n.group_key=p_group_key
  order by n.created_at desc;
end;
$$;

create or replace function public.hdg_delete_night(p_group_key text, p_night_id bigint)
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if not exists(select 1 from public.hdg_groups where group_key=p_group_key) then
    raise exception 'Invalid group access';
  end if;
  delete from public.hdg_nights
  where group_key=p_group_key and id=p_night_id;
end;
$$;

grant execute on function public.hdg_check_group(text) to anon;
grant execute on function public.hdg_save_live(text,text,jsonb) to anon;
grant execute on function public.hdg_get_live(text,text) to anon;
grant execute on function public.hdg_get_open_night(text) to anon;
grant execute on function public.hdg_close_night(text,jsonb) to anon;
grant execute on function public.hdg_get_old_nights(text) to anon;
grant execute on function public.hdg_delete_night(text,bigint) to anon;

-- Choose a strong access code, calculate its SHA-256, then run:
-- insert into public.hdg_groups(group_key,group_name)
-- values ('PASTE_SHA256_HASH_HERE','Harbu Darbu Gang');
